
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/**
 *
 * @author Exam
 */
public class planeSparesGUI extends javax.swing.JFrame {

    PlaneSpares[] arrSpares = new PlaneSpares[100];
    int c = 0;

    /**
     * Creates new form planeSparesGUI
     */
    public planeSparesGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaoutput = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        cmdDisplay = new javax.swing.JButton();
        sortPrice = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaoutput2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        txtAreaoutput.setColumns(20);
        txtAreaoutput.setRows(5);
        jScrollPane1.setViewportView(txtAreaoutput);

        jTextField1.setText("txtAreaoutput");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        cmdDisplay.setText("Read Data ");
        cmdDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(cmdDisplay);
        cmdDisplay.setBounds(20, 430, 120, 23);

        sortPrice.setText("Sort By Price");
        sortPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortPriceActionPerformed(evt);
            }
        });
        getContentPane().add(sortPrice);
        sortPrice.setBounds(150, 430, 120, 23);

        txtAreaoutput2.setColumns(20);
        txtAreaoutput2.setRows(5);
        jScrollPane3.setViewportView(txtAreaoutput2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 0, 780, 410);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 470);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 780, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


        try {
            Scanner sc = new Scanner(new FileReader("Spares.txt"));

            while (sc.hasNext()) {
                String line = sc.nextLine();

                Scanner scLine = new Scanner(line).useDelimiter(";");

                String code1 = scLine.next();
                String description1 = scLine.next();
                double costPrice1 = scLine.nextDouble();
                int noInStock1 = scLine.nextInt();

                arrSpares[c] = new PlaneSpares(code1, description1, costPrice1, noInStock1);
                c++;

            }//while
            sc.close();
        }//try
        catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error:" + e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cmdDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDisplayActionPerformed
        txtAreaoutput2.setText("");

        for (int i = 0; i < c; i++) {
            txtAreaoutput2.setText(txtAreaoutput2.getText() + "\n" + arrSpares[i].toString());
        }
    }//GEN-LAST:event_cmdDisplayActionPerformed

    private void sortPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortPriceActionPerformed



        txtAreaoutput2.setText("");

        for (int i = 0; i < c - 1; i++) {
            for (int j = i + 1; j < c; j++) {

                if (arrSpares[i].calcSellingPrice() > arrSpares[j].calcSellingPrice()) {
                    PlaneSpares temp = arrSpares[i];
                    arrSpares[i] = arrSpares[j];
                    arrSpares[j] = temp;
                }//if    
            }//for
        }//for

        cmdDisplayActionPerformed(evt);

    }//GEN-LAST:event_sortPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(planeSparesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(planeSparesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(planeSparesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(planeSparesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new planeSparesGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton sortPrice;
    private javax.swing.JTextArea txtAreaoutput;
    private javax.swing.JTextArea txtAreaoutput2;
    // End of variables declaration//GEN-END:variables
}
